### PR TITLE
Adding 2023 May workshop intro slides

### PR DESCRIPTION
**Pull request by Jen-OMalley**
The welcome slides were mostly updated already. (Thanks to @sjspielman, I assume!) Besides generating the PDF version, I mainly just double checked the updated dates and links, added a new ice breaker, swapped a couple of photos, and changed `CCDL` to `Data Lab` in a few spots. 

[**Google slides are here**](https://docs.google.com/presentation/d/1DoysGdsqoFiEuqtoFYIELVTsm6A0aJzq1cqKE2BeA9A/edit?usp=sharing).

### CODE REVIEW

**Review by sjspielman — COMMENTED** [review]
Hm, so I realize it's probably time for me to update my research interests given my, um, current total lack of interest in phylogenetics 😂 
I'm going to go tweak the slides now (ETA 1 minute), and then can you re-export the PDF?

**Comment by Jen-OMalley** [comment]
> Edit: slide has been updated! Ready for re-export, thanks!

Done!

**Review by sjspielman — APPROVED** [review]
👍

**Comment by Jen-OMalley** [comment]
> I think we can probably drop David from the slides... he isn't likely to show up since I don't think he ever has!
> 
> I'd also like to keep the icebreaker a bit lighter? A recent accomplishment seems potentially stress-inducing... Let's stick with books or pets or something like that.

Done!

**Comment by Jen-OMalley** [comment]
> I think we can probably drop David from the slides... he isn't likely to show up since I don't think he ever has!
> 
> I'd also like to keep the icebreaker a bit lighter? A recent accomplishment seems potentially stress-inducing... Let's stick with books or pets or something like that.

Done **@jashapiro**!

**Review by jashapiro — APPROVED** [review]
LGTM! Thanks for the updates

**Pull request merged**
